### ISSUE TITLE
BP - ImageCrop

### ISSUE THREAD

**Issue by Mitroz** [riganti/dotvvm#1637]
only windows targeting is supported. 

The type initializer for 'Gdip' threw an exception.
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
   at System.Drawing.LibraryResolver.EnsureRegistered()
   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---

**Comment by Mitroz** [comment]
IImageFactory implementation on SkiaSharp attached if anyone needs it. 
[SkiaSharpImageFactory.txt](https://github.com/riganti/dotvvm/files/11232058/SkiaSharpImageFactory.txt)
