### ISSUE TITLE
MiniProfile Crashing in NuGet Package Reference Version

### ISSUE THREAD

**Issue by scottkuhl** [riganti/dotvvm#475]
I tried adding Mini-Profiler to my app and kept getting the following error on app.UseDotVVM<DotvvmStartup>(env.ContentRootPath);

Could not load type 'Settings' from assembly 'MiniProfiler.Shared

So I downloaded the DotVVM source and ran the DotVVM.Samples.MiniProfiler.AspNetCore sample which works fine.  I was finely able to reproduce the issue in the sample project by removing the project references to DotVVM and adding the NuGet package reference to DotVVM.Tracing.MiniProfiler.AspNetCore instead.

Here is the error produced from the sample code:

System.TypeLoadException occurred
  HResult=0x80131522
  Message=Could not load type 'Settings' from assembly 'MiniProfiler.Shared, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b44f9351044011a3'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at DotVVM.Tracing.MiniProfiler.AspNetCore.MiniProfilerSetup.Configure(DotvvmConfiguration config)
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseDotVVM(IApplicationBuilder app, String applicationRootPath, Nullable`1 useErrorPages)
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseDotVVM[TStartup](IApplicationBuilder app, String applicationRootPath, Nullable`1 useErrorPages)
   at DotVVM.Samples.MiniProfiler.AspNetCore.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache) in C:\Users\scott\Source\Repos\dotvvm\src\DotVVM.Samples.MiniProfiler.AspNetCore\Startup.cs:line 44

**Comment by exyi** [comment]
It seems like a version mismatch in the current published version, but it seems to be fixed in `master` branch. Maybe we could republish the old release, but I think it would be much better to finally release the 2.0 version.
