### ISSUE TITLE
InvalidProgramException on Windows 7 .NET FW 4.5.1

### ISSUE THREAD

**Issue by holajan** [riganti/dotvvm#83]
On  Windows 7 SP1 and Windows Server 2008 SP2 with only .NET Framework 4.5.1 this error is displayed:
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
at System.Collections.Immutable.SecurePooledObject`1.Use[TCaller](TCaller& caller)
at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator.PushLeft(SortedInt32KeyNode`1 node)
at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator..ctor(SortedInt32KeyNode`1 root)
at System.Collections.Immutable.ImmutableHashSet`1.Enumerator..ctor(SortedInt32KeyNode`1 root, Builder builder)
at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.CheckInterfaces(DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.<>c__DisplayClass45_0.<ForceComplete>b__0(Int32 i)
at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass6_0`1.<WithCurrentUICulture>b__0(T param)
at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
at System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)
--- End of inner exception stack trace ---

Upgrading .NET Framework from 4.5.1 to 4.5.2 solved the issue.
More info here https://github.com/dotnet/roslyn/issues/110 and here https://github.com/dotnet/corefx/issues/320

Consider changing Redwood.Framework targeting to .NET Framework 4.5.2.

**Comment by tomasherceg** [comment]
Can you please test whether the current version still does the issue?
The latest version on NuGet targets the RTM Roslyn version.

**Comment by holajan** [comment]
Yes, now It seems that it working fine.
