### ISSUE TITLE
Install with Visual Studio 19 Preview

### ISSUE THREAD

**Issue by careLearning** [riganti/dotvvm#863]
Hello,

Is it possible to install this extension for VS 19 Preview?  When I install it, this is the log:

`7/21/2020 10:11:23 AM - Searching for applicable products...
7/21/2020 10:11:23 AM - Found installed product - Global Location
7/21/2020 10:11:23 AM - Found installed product - Visual Studio Professional 2019 Preview
7/21/2020 10:11:23 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---`

Thanks!

**Comment by quigamdev** [comment]
Hello, 
please try this VSIX package. https://storage.dotvvm.com/public/DotVVM.Integration.VisualStudio.VS2019-Preview.2.4.204.0.vsix
This package is compatible with Visual Studio 2019 Preview (v16.7.0 Preview 5.0). 

It is a preview version, so please, be aware that errors can occur. If occurs feel free to contact us.

**Comment by quigamdev** [comment]
The solution to this issue was already deployed. So I am closing this issue. If there is any further problem with VS compatibility do not hesitate to contact us.
